# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregated_stats.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.AggregatedStats" do
    optional :averageAssists, :int32, 1
    optional :averageChampionsKilled, :int32, 2
    optional :averageCombatPlayerScore, :int32, 3
    optional :averageNodeCapture, :int32, 4
    optional :averageNodeCaptureAssist, :int32, 5
    optional :averageNodeNeutralize, :int32, 6
    optional :averageNodeNeutralizeAssist, :int32, 7
    optional :averageNumDeaths, :int32, 8
    optional :averageObjectivePlayerScore, :int32, 9
    optional :averageTeamObjective, :int32, 10
    optional :averageTotalPlayerScore, :int32, 11
    optional :botGamesPlayed, :int32, 12
    optional :killingSpree, :int32, 13
    optional :maxAssists, :int32, 14
    optional :maxChampionsKilled, :int32, 15
    optional :maxCombatPlayerScore, :int32, 16
    optional :maxLargestCriticalStrike, :int32, 17
    optional :maxLargestKillingSpree, :int32, 18
    optional :maxNodeCapture, :int32, 19
    optional :maxNodeCaptureAssist, :int32, 20
    optional :maxNodeNeutralize, :int32, 21
    optional :maxNodeNeutralizeAssist, :int32, 22
    optional :maxNumDeaths, :int32, 23
    optional :maxObjectivePlayerScore, :int32, 24
    optional :maxTeamObjective, :int32, 25
    optional :maxTimePlayed, :int32, 26
    optional :maxTimeSpentLiving, :int32, 27
    optional :maxTotalPlayerScore, :int32, 28
    optional :mostChampionKillsPerSession, :int32, 29
    optional :mostSpellsCast, :int32, 30
    optional :normalGamesPlayed, :int32, 31
    optional :rankedPremadeGamesPlayed, :int32, 32
    optional :rankedSoloGamesPlayed, :int32, 33
    optional :totalAssists, :int32, 34
    optional :totalChampionKills, :int32, 35
    optional :totalDamageDealt, :int32, 36
    optional :totalDamageTaken, :int32, 37
    optional :totalDeathsPerSession, :int32, 38
    optional :totalDoubleKills, :int32, 39
    optional :totalFirstBlood, :int32, 40
    optional :totalGoldEarned, :int32, 41
    optional :totalHeal, :int32, 42
    optional :totalMagicDamageDealt, :int32, 43
    optional :totalMinionKills, :int32, 44
    optional :totalNeutralMinionsKilled, :int32, 45
    optional :totalNodeCapture, :int32, 46
    optional :totalNodeNeutralize, :int32, 47
    optional :totalPentaKills, :int32, 48
    optional :totalPhysicalDamageDealt, :int32, 49
    optional :totalQuadraKills, :int32, 50
    optional :totalSessionsLost, :int32, 51
    optional :totalSessionsPlayed, :int32, 52
    optional :totalSessionsWon, :int32, 53
    optional :totalTripleKills, :int32, 54
    optional :totalTurretsKilled, :int32, 55
    optional :totalUnrealKills, :int32, 56
  end
end

module RiotAPI
  module Protos
    AggregatedStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.AggregatedStats").msgclass
  end
end
