# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_data.proto

require 'google/protobuf'

require 'gold_pb'
require 'image_pb'
require 'meta_data_pb'
require 'basic_data_stats_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.BasicData" do
    optional :colloq, :string, 1
    optional :consumeOnFull, :bool, 2
    optional :consumed, :bool, 3
    optional :depth, :int32, 4
    optional :description, :string, 5
    repeated :from, :string, 6
    optional :gold, :message, 7, "riotAPI.protos.Gold"
    optional :group, :string, 8
    optional :hideFromAll, :bool, 9
    optional :id, :int32, 10
    optional :image, :message, 11, "riotAPI.protos.Image"
    optional :inStore, :bool, 12
    repeated :into, :string, 13
    map :maps, :string, :bool, 14
    optional :name, :string, 15
    optional :plaintext, :string, 16
    optional :requiredChampion, :string, 17
    optional :rune, :message, 18, "riotAPI.protos.MetaData"
    optional :sanitizedDescription, :string, 19
    optional :specialRecipe, :int32, 20
    optional :stacks, :int32, 21
    optional :stats, :message, 22, "riotAPI.protos.BasicDataStats"
    repeated :tags, :string, 23
  end
end

module RiotAPI
  module Protos
    BasicData = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.BasicData").msgclass
  end
end
