# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_data_stats.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.BasicDataStats" do
    optional :FlatArmorMod, :double, 1
    optional :FlatAttackSpeedMod, :double, 2
    optional :FlatBlockMod, :double, 3
    optional :FlatCritChanceMod, :double, 4
    optional :FlatCritDamageMod, :double, 5
    optional :FlatEXPBonus, :double, 6
    optional :FlatEnergyPoolMod, :double, 7
    optional :FlatEnergyRegenMod, :double, 8
    optional :FlatHPPoolMod, :double, 9
    optional :FlatHPRegenMod, :double, 10
    optional :FlatMPPoolMod, :double, 11
    optional :FlatMPRegenMod, :double, 12
    optional :FlatMagicDamageMod, :double, 13
    optional :FlatMovementSpeedMod, :double, 14
    optional :FlatPhysicalDamageMod, :double, 15
    optional :FlatSpellBlockMod, :double, 16
    optional :PercentArmorMod, :double, 17
    optional :PercentAttackSpeedMod, :double, 18
    optional :PercentBlockMod, :double, 19
    optional :PercentCritChanceMod, :double, 20
    optional :PercentCritDamageMod, :double, 21
    optional :PercentDodgeMod, :double, 22
    optional :PercentEXPBonus, :double, 23
    optional :PercentHPPoolMod, :double, 24
    optional :PercentHPRegenMod, :double, 25
    optional :PercentLifeStealMod, :double, 26
    optional :PercentMPPoolMod, :double, 27
    optional :PercentMPRegenMod, :double, 28
    optional :PercentMagicDamageMod, :double, 29
    optional :PercentMovementSpeedMod, :double, 30
    optional :PercentPhysicalDamageMod, :double, 31
    optional :PercentSpellBlockMod, :double, 32
    optional :PercentSpellVampMod, :double, 33
    optional :rFlatArmorModPerLevel, :double, 34
    optional :rFlatArmorPenetrationMod, :double, 35
    optional :rFlatArmorPenetrationModPerLevel, :double, 36
    optional :rFlatCritChanceModPerLevel, :double, 37
    optional :rFlatCritDamageModPerLevel, :double, 38
    optional :rFlatDodgeMod, :double, 39
    optional :rFlatDodgeModPerLevel, :double, 40
    optional :rFlatEnergyModPerLevel, :double, 41
    optional :rFlatEnergyRegenModPerLevel, :double, 42
    optional :rFlatGoldPer10Mod, :double, 43
    optional :rFlatHPModPerLevel, :double, 44
    optional :rFlatHPRegenModPerLevel, :double, 45
    optional :rFlatMPModPerLevel, :double, 46
    optional :rFlatMPRegenModPerLevel, :double, 47
    optional :rFlatMagicDamageModPerLevel, :double, 48
    optional :rFlatMagicPenetrationMod, :double, 49
    optional :rFlatMagicPenetrationModPerLevel, :double, 50
    optional :rFlatMovementSpeedModPerLevel, :double, 51
    optional :rFlatPhysicalDamageModPerLevel, :double, 52
    optional :rFlatSpellBlockModPerLevel, :double, 53
    optional :rFlatTimeDeadMod, :double, 54
    optional :rFlatTimeDeadModPerLevel, :double, 55
    optional :rPercentArmorPenetrationMod, :double, 56
    optional :rPercentArmorPenetrationModPerLevel, :double, 57
    optional :rPercentAttackSpeedModPerLevel, :double, 58
    optional :rPercentCooldownMod, :double, 59
    optional :rPercentCooldownModPerLevel, :double, 60
    optional :rPercentMagicPenetrationMod, :double, 61
    optional :rPercentMagicPenetrationModPerLevel, :double, 62
    optional :rPercentMovementSpeedModPerLevel, :double, 63
    optional :rPercentTimeDeadMod, :double, 64
    optional :rPercentTimeDeadModPerLevel, :double, 65
  end
end

module RiotAPI
  module Protos
    BasicDataStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.BasicDataStats").msgclass
  end
end
