# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block_item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.BlockItem" do
    optional :count, :int32, 1
    optional :id, :int32, 2
  end
end

module RiotAPI
  module Protos
    BlockItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.BlockItem").msgclass
  end
end
