# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto

require 'google/protobuf'

require 'block_item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Block" do
    repeated :items, :message, 1, "riotAPI.protos.BlockItem"
    optional :recMath, :bool, 2
    optional :type, :string, 3
  end
end

module RiotAPI
  module Protos
    Block = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Block").msgclass
  end
end
