# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: champion_spell.proto

require 'google/protobuf'

require 'image_pb'
require 'google/protobuf/any_pb'
require 'level_tip_pb'
require 'spell_vars_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ChampionSpell" do
    repeated :altimages, :message, 1, "riotAPI.protos.Image"
    repeated :cooldown, :double, 2
    optional :cooldownBurn, :string, 3
    repeated :cost, :int32, 4
    optional :costBurn, :string, 5
    optional :costType, :string, 6
    optional :description, :string, 7
    repeated :effect, :message, 8, "google.protobuf.Any"
    repeated :effectBurn, :string, 9
    optional :image, :message, 10, "riotAPI.protos.Image"
    optional :key, :string, 11
    optional :leveltip, :message, 12, "riotAPI.protos.LevelTip"
    optional :maxrank, :int32, 13
    optional :name, :string, 14
    optional :range, :message, 15, "google.protobuf.Any"
    optional :rangeBurn, :string, 16
    optional :resource, :string, 17
    optional :sanitizedDescription, :string, 18
    optional :sanitizedTooltip, :string, 19
    optional :tooltip, :string, 20
    repeated :vars, :message, 21, "riotAPI.protos.SpellVars"
  end
end

module RiotAPI
  module Protos
    ChampionSpell = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ChampionSpell").msgclass
  end
end
