# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: champion.proto

require 'google/protobuf'

require 'image_pb'
require 'info_pb'
require 'passive_pb'
require 'recommended_pb'
require 'skin_pb'
require 'champion_spell_pb'
require 'stats_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Champion" do
    optional :active, :bool, 1
    optional :botEnabled, :bool, 2
    optional :botMmEnabled, :bool, 3
    optional :freeToPlay, :bool, 4
    optional :id, :int32, 5
    optional :rankedPlayEnabled, :bool, 6
    repeated :allytips, :string, 7
    optional :blurb, :string, 8
    repeated :enemytips, :string, 9
    optional :image, :message, 10, "riotAPI.protos.Image"
    optional :info, :message, 11, "riotAPI.protos.Info"
    optional :key, :string, 12
    optional :lore, :string, 13
    optional :name, :string, 14
    optional :partype, :string, 15
    optional :passive, :message, 16, "riotAPI.protos.Passive"
    repeated :recommended, :message, 17, "riotAPI.protos.Recommended"
    repeated :skins, :message, 18, "riotAPI.protos.Skin"
    repeated :spells, :message, 19, "riotAPI.protos.ChampionSpell"
    optional :stats, :message, 20, "riotAPI.protos.Stats"
    repeated :tags, :string, 21
    optional :title, :string, 22
  end
end

module RiotAPI
  module Protos
    Champion = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Champion").msgclass
  end
end
