# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: champion_mastery.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ChampionMastery" do
    optional :championId, :int64, 1
    optional :championLevel, :int32, 2
    optional :championPoints, :int32, 3
    optional :championPointsSinceLastLevel, :int64, 4
    optional :championPointsUntilNextLevel, :int64, 5
    optional :chestGranted, :bool, 6
    optional :lastPlayTime, :int64, 7
    optional :playerId, :int64, 8
  end
end

module RiotAPI
  module Protos
    ChampionMastery = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ChampionMastery").msgclass
  end
end
