# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: champion_list.proto

require 'google/protobuf'

require 'champion_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ChampionList" do
    repeated :champions, :message, 1, "riotAPI.protos.Champion"
    map :data, :string, :message, 2, "riotAPI.protos.Champion"
    optional :format, :string, 3
    map :keys, :string, :string, 4
    optional :type, :string, 5
    optional :version, :string, 6
  end
end

module RiotAPI
  module Protos
    ChampionList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ChampionList").msgclass
  end
end
