# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: current_game_participant.proto

require 'google/protobuf'

require 'mastery_pb'
require 'rune_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.CurrentGameParticipant" do
    optional :bot, :bool, 1
    optional :championId, :int64, 2
    repeated :masteries, :message, 3, "riotAPI.protos.Mastery"
    optional :profileIconId, :int64, 4
    repeated :runes, :message, 5, "riotAPI.protos.Rune"
    optional :spell1Id, :int64, 6
    optional :spell2Id, :int64, 7
    optional :summonerId, :int64, 8
    optional :summonerName, :string, 9
    optional :teamId, :int64, 10
  end
end

module RiotAPI
  module Protos
    CurrentGameParticipant = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.CurrentGameParticipant").msgclass
  end
end
