# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featured_game_info.proto

require 'google/protobuf'

require 'banned_champion_pb'
require 'observer_pb'
require 'participant_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.FeaturedGameInfo" do
    repeated :bannedChampions, :message, 1, "riotAPI.protos.BannedChampion"
    optional :gameId, :int64, 2
    optional :gameLength, :int64, 3
    optional :gameMode, :string, 4
    optional :gameQueueConfigId, :int64, 5
    optional :gameStartTime, :int64, 6
    optional :gameType, :string, 7
    optional :mapId, :int64, 8
    optional :observers, :message, 9, "riotAPI.protos.Observer"
    repeated :participants, :message, 10, "riotAPI.protos.Participant"
    optional :platformId, :string, 11
  end
end

module RiotAPI
  module Protos
    FeaturedGameInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.FeaturedGameInfo").msgclass
  end
end
