# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featured_games.proto

require 'google/protobuf'

require 'featured_game_info_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.FeaturedGames" do
    optional :clientRefreshInterval, :int64, 1
    repeated :gameList, :message, 2, "riotAPI.protos.FeaturedGameInfo"
  end
end

module RiotAPI
  module Protos
    FeaturedGames = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.FeaturedGames").msgclass
  end
end
