# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto

require 'google/protobuf'

require 'event_pb'
require 'participant_frame_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Frame" do
    repeated :events, :message, 1, "riotAPI.protos.Event"
    map :participantFrames, :string, :message, 2, "riotAPI.protos.ParticipantFrame"
    optional :timestamp, :int64, 3
  end
end

module RiotAPI
  module Protos
    Frame = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Frame").msgclass
  end
end
