# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

require 'google/protobuf'

require 'player_pb'
require 'raw_stats_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Game" do
    optional :championId, :int32, 1
    optional :createDate, :int64, 2
    repeated :fellowPlayers, :message, 3, "riotAPI.protos.Player"
    optional :gameId, :int64, 4
    optional :gameMode, :string, 5
    optional :gameType, :string, 6
    optional :invalid, :bool, 7
    optional :ipEarned, :int32, 8
    optional :level, :int32, 9
    optional :mapId, :int32, 10
    optional :spell1, :int32, 11
    optional :spell2, :int32, 12
    optional :stats, :message, 13, "riotAPI.protos.RawStats"
    optional :subType, :string, 14
    optional :teamId, :int32, 15
  end
end

module RiotAPI
  module Protos
    Game = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Game").msgclass
  end
end
