# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gold.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Gold" do
    optional :base, :int32, 1
    optional :purchasable, :bool, 2
    optional :sell, :int32, 3
    optional :total, :int32, 4
  end
end

module RiotAPI
  module Protos
    Gold = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Gold").msgclass
  end
end
