# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Group" do
    optional :MaxGroupOwnable, :string, 1
    optional :key, :string, 2
  end
end

module RiotAPI
  module Protos
    Group = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Group").msgclass
  end
end
