# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Image" do
    optional :full, :string, 1
    optional :group, :string, 2
    optional :h, :int32, 3
    optional :sprite, :string, 4
    optional :w, :int32, 5
    optional :x, :int32, 6
    optional :y, :int32, 7
  end
end

module RiotAPI
  module Protos
    Image = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Image").msgclass
  end
end
