# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: incident.proto

require 'google/protobuf'

require 'message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Incident" do
    optional :active, :bool, 1
    optional :created_at, :string, 2
    optional :id, :int64, 3
    repeated :updates, :message, 4, "riotAPI.protos.Message"
  end
end

module RiotAPI
  module Protos
    Incident = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Incident").msgclass
  end
end
