# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_list.proto

require 'google/protobuf'

require 'basic_data_pb'
require 'item_pb'
require 'group_pb'
require 'item_tree_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ItemList" do
    optional :basic, :message, 1, "riotAPI.protos.BasicData"
    map :data, :string, :message, 2, "riotAPI.protos.Item"
    repeated :groups, :message, 3, "riotAPI.protos.Group"
    repeated :tree, :message, 4, "riotAPI.protos.ItemTree"
    optional :type, :string, 5
    optional :version, :string, 6
  end
end

module RiotAPI
  module Protos
    ItemList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ItemList").msgclass
  end
end
