# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language_strings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.LanguageStrings" do
    map :data, :string, :string, 1
    optional :type, :string, 2
    optional :version, :string, 3
  end
end

module RiotAPI
  module Protos
    LanguageStrings = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.LanguageStrings").msgclass
  end
end
