# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: league.proto

require 'google/protobuf'

require 'league_entry_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.League" do
    repeated :entries, :message, 1, "riotAPI.protos.LeagueEntry"
    optional :name, :string, 2
    optional :participantId, :string, 3
    optional :queue, :string, 4
    optional :tier, :string, 5
  end
end

module RiotAPI
  module Protos
    League = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.League").msgclass
  end
end
