# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: league_entry.proto

require 'google/protobuf'

require 'mini_series_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.LeagueEntry" do
    optional :division, :string, 1
    optional :isFreshBlood, :bool, 2
    optional :isHotStreak, :bool, 3
    optional :isInactive, :bool, 4
    optional :isVeteran, :bool, 5
    optional :leaguePoints, :int32, 6
    optional :losses, :int32, 7
    optional :miniSeries, :message, 8, "riotAPI.protos.MiniSeries"
    optional :playerOrTeamId, :string, 9
    optional :playerOrTeamName, :string, 10
    optional :playstyle, :string, 11
    optional :wins, :int32, 12
  end
end

module RiotAPI
  module Protos
    LeagueEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.LeagueEntry").msgclass
  end
end
