# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: level_tip.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.LevelTip" do
    repeated :effect, :string, 1
    repeated :label, :string, 2
  end
end

module RiotAPI
  module Protos
    LevelTip = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.LevelTip").msgclass
  end
end
