# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_data.proto

require 'google/protobuf'

require 'map_details_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MapData" do
    map :data, :string, :message, 1, "riotAPI.protos.MapDetails"
    optional :type, :string, 2
    optional :version, :string, 3
  end
end

module RiotAPI
  module Protos
    MapData = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MapData").msgclass
  end
end
