# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery_page.proto

require 'google/protobuf'

require 'mastery_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MasteryPage" do
    optional :current, :bool, 1
    optional :id, :int64, 2
    repeated :masteries, :message, 3, "riotAPI.protos.Mastery"
    optional :name, :string, 4
  end
end

module RiotAPI
  module Protos
    MasteryPage = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MasteryPage").msgclass
  end
end
