# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery_tree_list.proto

require 'google/protobuf'

require 'mastery_tree_item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MasteryTreeList" do
    repeated :masteryTreeItems, :message, 1, "riotAPI.protos.MasteryTreeItem"
  end
end

module RiotAPI
  module Protos
    MasteryTreeList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MasteryTreeList").msgclass
  end
end
