# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery_tree_item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MasteryTreeItem" do
    optional :masteryId, :int32, 1
    optional :prereq, :string, 2
  end
end

module RiotAPI
  module Protos
    MasteryTreeItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MasteryTreeItem").msgclass
  end
end
