# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery_tree.proto

require 'google/protobuf'

require 'mastery_tree_list_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MasteryTree" do
    repeated :Cunning, :message, 1, "riotAPI.protos.MasteryTreeList"
    repeated :Ferocity, :message, 2, "riotAPI.protos.MasteryTreeList"
    repeated :Resolve, :message, 3, "riotAPI.protos.MasteryTreeList"
  end
end

module RiotAPI
  module Protos
    MasteryTree = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MasteryTree").msgclass
  end
end
