# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery.proto

require 'google/protobuf'

require 'image_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Mastery" do
    optional :masteryId, :int64, 1
    optional :rank, :int32, 2
    repeated :description, :string, 3
    optional :id, :int32, 4
    optional :image, :message, 5, "riotAPI.protos.Image"
    optional :masteryTree, :string, 6
    optional :name, :string, 7
    optional :prereq, :string, 8
    optional :ranks, :int32, 9
    repeated :sanitizedDescription, :string, 10
  end
end

module RiotAPI
  module Protos
    Mastery = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Mastery").msgclass
  end
end
