# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mastery_list.proto

require 'google/protobuf'

require 'mastery_pb'
require 'mastery_tree_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MasteryList" do
    map :data, :string, :message, 1, "riotAPI.protos.Mastery"
    optional :tree, :message, 2, "riotAPI.protos.MasteryTree"
    optional :type, :string, 3
    optional :version, :string, 4
  end
end

module RiotAPI
  module Protos
    MasteryList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MasteryList").msgclass
  end
end
