# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_list.proto

require 'google/protobuf'

require 'match_reference_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MatchList" do
    optional :endIndex, :int32, 1
    repeated :matches, :message, 2, "riotAPI.protos.MatchReference"
    optional :startIndex, :int32, 3
    optional :totalGames, :int32, 4
  end
end

module RiotAPI
  module Protos
    MatchList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MatchList").msgclass
  end
end
