# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_history_summary.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MatchHistorySummary" do
    optional :assists, :int32, 1
    optional :date, :int64, 2
    optional :deaths, :int32, 3
    optional :gameId, :int64, 4
    optional :gameMode, :string, 5
    optional :invalid, :bool, 6
    optional :kills, :int32, 7
    optional :mapId, :int32, 8
    optional :opposingTeamKills, :int32, 9
    optional :opposingTeamName, :string, 10
    optional :win, :bool, 11
  end
end

module RiotAPI
  module Protos
    MatchHistorySummary = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MatchHistorySummary").msgclass
  end
end
