# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match_reference.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MatchReference" do
    optional :champion, :int64, 1
    optional :lane, :string, 2
    optional :matchId, :int64, 3
    optional :platformId, :string, 4
    optional :queue, :string, 5
    optional :region, :string, 6
    optional :role, :string, 7
    optional :season, :string, 8
    optional :timestamp, :int64, 9
  end
end

module RiotAPI
  module Protos
    MatchReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MatchReference").msgclass
  end
end
