# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta_data.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.MetaData" do
    optional :isRune, :bool, 1
    optional :tier, :string, 2
    optional :type, :string, 3
  end
end

module RiotAPI
  module Protos
    MetaData = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.MetaData").msgclass
  end
end
