# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant_frame.proto

require 'google/protobuf'

require 'position_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ParticipantFrame" do
    optional :currentGold, :int32, 1
    optional :dominionScore, :int32, 2
    optional :jungleMinionsKilled, :int32, 3
    optional :level, :int32, 4
    optional :minionsKilled, :int32, 5
    optional :participantId, :int32, 6
    optional :position, :message, 7, "riotAPI.protos.Position"
    optional :teamScore, :int32, 8
    optional :totalGold, :int32, 9
    optional :xp, :int32, 10
  end
end

module RiotAPI
  module Protos
    ParticipantFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ParticipantFrame").msgclass
  end
end
