# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant_identity.proto

require 'google/protobuf'

require 'player_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ParticipantIdentity" do
    optional :participantId, :int32, 1
    optional :player, :message, 2, "riotAPI.protos.Player"
  end
end

module RiotAPI
  module Protos
    ParticipantIdentity = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ParticipantIdentity").msgclass
  end
end
