# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant_timeline_data.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ParticipantTimelineData" do
    optional :tenToTwenty, :double, 1
    optional :thirtyToEnd, :double, 2
    optional :twentyToThirty, :double, 3
    optional :zeroToTen, :double, 4
  end
end

module RiotAPI
  module Protos
    ParticipantTimelineData = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ParticipantTimelineData").msgclass
  end
end
