# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant_timeline.proto

require 'google/protobuf'

require 'participant_timeline_data_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ParticipantTimeline" do
    optional :ancientGolemAssistsPerMinCounts, :message, 1, "riotAPI.protos.ParticipantTimelineData"
    optional :ancientGolemKillsPerMinCounts, :message, 2, "riotAPI.protos.ParticipantTimelineData"
    optional :assistedLaneDeathsPerMinDeltas, :message, 3, "riotAPI.protos.ParticipantTimelineData"
    optional :assistedLaneKillsPerMinDeltas, :message, 4, "riotAPI.protos.ParticipantTimelineData"
    optional :baronAssistsPerMinCounts, :message, 5, "riotAPI.protos.ParticipantTimelineData"
    optional :baronKillsPerMinCounts, :message, 6, "riotAPI.protos.ParticipantTimelineData"
    optional :creepsPerMinDeltas, :message, 7, "riotAPI.protos.ParticipantTimelineData"
    optional :csDiffPerMinDeltas, :message, 8, "riotAPI.protos.ParticipantTimelineData"
    optional :damageTakenDiffPerMinDeltas, :message, 9, "riotAPI.protos.ParticipantTimelineData"
    optional :damageTakenPerMinDeltas, :message, 10, "riotAPI.protos.ParticipantTimelineData"
    optional :dragonAssistsPerMinCounts, :message, 11, "riotAPI.protos.ParticipantTimelineData"
    optional :dragonKillsPerMinCounts, :message, 12, "riotAPI.protos.ParticipantTimelineData"
    optional :elderLizardAssistsPerMinCounts, :message, 13, "riotAPI.protos.ParticipantTimelineData"
    optional :elderLizardKillsPerMinCounts, :message, 14, "riotAPI.protos.ParticipantTimelineData"
    optional :goldPerMinDeltas, :message, 15, "riotAPI.protos.ParticipantTimelineData"
    optional :inhibitorAssistsPerMinCounts, :message, 16, "riotAPI.protos.ParticipantTimelineData"
    optional :inhibitorKillsPerMinCounts, :message, 17, "riotAPI.protos.ParticipantTimelineData"
    optional :lane, :string, 18
    optional :role, :string, 19
    optional :towerAssistsPerMinCounts, :message, 20, "riotAPI.protos.ParticipantTimelineData"
    optional :towerKillsPerMinCounts, :message, 21, "riotAPI.protos.ParticipantTimelineData"
    optional :towerKillsPerMinDeltas, :message, 22, "riotAPI.protos.ParticipantTimelineData"
    optional :vilemawAssistsPerMinCounts, :message, 23, "riotAPI.protos.ParticipantTimelineData"
    optional :vilemawKillsPerMinCounts, :message, 24, "riotAPI.protos.ParticipantTimelineData"
    optional :wardsPerMinDeltas, :message, 25, "riotAPI.protos.ParticipantTimelineData"
    optional :xpDiffPerMinDeltas, :message, 26, "riotAPI.protos.ParticipantTimelineData"
    optional :xpPerMinDeltas, :message, 27, "riotAPI.protos.ParticipantTimelineData"
  end
end

module RiotAPI
  module Protos
    ParticipantTimeline = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ParticipantTimeline").msgclass
  end
end
