# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: participant_stats.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ParticipantStats" do
    optional :assists, :int64, 1
    optional :champLevel, :int64, 2
    optional :combatPlayerScore, :int64, 3
    optional :deaths, :int64, 4
    optional :doubleKills, :int64, 5
    optional :firstBloodAssist, :bool, 6
    optional :firstBloodKill, :bool, 7
    optional :firstInhibitorAssist, :bool, 8
    optional :firstInhibitorKill, :bool, 9
    optional :firstTowerAssist, :bool, 10
    optional :firstTowerKill, :bool, 11
    optional :goldEarned, :int64, 12
    optional :goldSpent, :int64, 13
    optional :inhibitorKills, :int64, 14
    optional :item0, :int64, 15
    optional :item1, :int64, 16
    optional :item2, :int64, 17
    optional :item3, :int64, 18
    optional :item4, :int64, 19
    optional :item5, :int64, 20
    optional :item6, :int64, 21
    optional :killingSprees, :int64, 22
    optional :kills, :int64, 23
    optional :largestCriticalStrike, :int64, 24
    optional :largestKillingSpree, :int64, 25
    optional :largestMultiKill, :int64, 26
    optional :magicDamageDealt, :int64, 27
    optional :magicDamageDealtToChampions, :int64, 28
    optional :magicDamageTaken, :int64, 29
    optional :minionsKilled, :int64, 30
    optional :neutralMinionsKilled, :int64, 31
    optional :neutralMinionsKilledEnemyJungle, :int64, 32
    optional :neutralMinionsKilledTeamJungle, :int64, 33
    optional :nodeCapture, :int64, 34
    optional :nodeCaptureAssist, :int64, 35
    optional :nodeNeutralize, :int64, 36
    optional :nodeNeutralizeAssist, :int64, 37
    optional :objectivePlayerScore, :int64, 38
    optional :pentaKills, :int64, 39
    optional :physicalDamageDealt, :int64, 40
    optional :physicalDamageDealtToChampions, :int64, 41
    optional :physicalDamageTaken, :int64, 42
    optional :quadraKills, :int64, 43
    optional :sightWardsBoughtInGame, :int64, 44
    optional :teamObjective, :int64, 45
    optional :totalDamageDealt, :int64, 46
    optional :totalDamageDealtToChampions, :int64, 47
    optional :totalDamageTaken, :int64, 48
    optional :totalHeal, :int64, 49
    optional :totalPlayerScore, :int64, 50
    optional :totalScoreRank, :int64, 51
    optional :totalTimeCrowdControlDealt, :int64, 52
    optional :totalUnitsHealed, :int64, 53
    optional :towerKills, :int64, 54
    optional :tripleKills, :int64, 55
    optional :trueDamageDealt, :int64, 56
    optional :trueDamageDealtToChampions, :int64, 57
    optional :trueDamageTaken, :int64, 58
    optional :unrealKills, :int64, 59
    optional :visionWardsBoughtInGame, :int64, 60
    optional :wardsKilled, :int64, 61
    optional :wardsPlaced, :int64, 62
    optional :winner, :bool, 63
  end
end

module RiotAPI
  module Protos
    ParticipantStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ParticipantStats").msgclass
  end
end
