# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: passive.proto

require 'google/protobuf'

require 'image_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Passive" do
    optional :description, :string, 1
    optional :image, :message, 2, "riotAPI.protos.Image"
    optional :name, :string, 3
    optional :sanitizedDescription, :string, 4
  end
end

module RiotAPI
  module Protos
    Passive = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Passive").msgclass
  end
end
