# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_stats_summary_list.proto

require 'google/protobuf'

require 'player_stats_summary_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.PlayerStatsSummaryList" do
    repeated :playerStatSummaries, :message, 1, "riotAPI.protos.PlayerStatsSummary"
    optional :summonerId, :int64, 2
  end
end

module RiotAPI
  module Protos
    PlayerStatsSummaryList = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.PlayerStatsSummaryList").msgclass
  end
end
