# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider_registration_parameters.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ProviderRegistrationParameters" do
    optional :region, :string, 1
    optional :url, :string, 2
  end
end

module RiotAPI
  module Protos
    ProviderRegistrationParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ProviderRegistrationParameters").msgclass
  end
end
