# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ranked_stats.proto

require 'google/protobuf'

require 'champion_stats_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.RankedStats" do
    repeated :champions, :message, 1, "riotAPI.protos.ChampionStats"
    optional :modifyDate, :int64, 2
    optional :summonerId, :int64, 3
  end
end

module RiotAPI
  module Protos
    RankedStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.RankedStats").msgclass
  end
end
