# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realm.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Realm" do
    optional :cdn, :string, 1
    optional :css, :string, 2
    optional :dd, :string, 3
    optional :l, :string, 4
    optional :lg, :string, 5
    map :n, :string, :string, 6
    optional :profileiconmax, :int32, 7
    optional :store, :string, 8
    optional :v, :string, 9
  end
end

module RiotAPI
  module Protos
    Realm = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Realm").msgclass
  end
end
