# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recent_games.proto

require 'google/protobuf'

require 'game_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.RecentGames" do
    repeated :games, :message, 1, "riotAPI.protos.Game"
    optional :summonerId, :int64, 2
  end
end

module RiotAPI
  module Protos
    RecentGames = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.RecentGames").msgclass
  end
end
