# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rune_page.proto

require 'google/protobuf'

require 'rune_slot_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.RunePage" do
    optional :current, :bool, 1
    optional :id, :int64, 2
    optional :name, :string, 3
    repeated :slots, :message, 4, "riotAPI.protos.RuneSlot"
  end
end

module RiotAPI
  module Protos
    RunePage = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.RunePage").msgclass
  end
end
