# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rune_slot.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.RuneSlot" do
    optional :runeId, :int32, 1
    optional :runeSlotId, :int32, 2
  end
end

module RiotAPI
  module Protos
    RuneSlot = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.RuneSlot").msgclass
  end
end
