# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rune_pages.proto

require 'google/protobuf'

require 'rune_page_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.RunePages" do
    repeated :pages, :message, 1, "riotAPI.protos.RunePage"
    optional :summonerId, :int64, 2
  end
end

module RiotAPI
  module Protos
    RunePages = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.RunePages").msgclass
  end
end
