# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

require 'incident_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Service" do
    repeated :incidents, :message, 1, "riotAPI.protos.Incident"
    optional :name, :string, 2
    optional :slug, :string, 3
    optional :status, :string, 4
  end
end

module RiotAPI
  module Protos
    Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Service").msgclass
  end
end
