# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Shard" do
    optional :hostname, :string, 1
    repeated :locales, :string, 2
    optional :name, :string, 3
    optional :region_tag, :string, 4
    optional :slug, :string, 5
  end
end

module RiotAPI
  module Protos
    Shard = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Shard").msgclass
  end
end
