# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shard_status.proto

require 'google/protobuf'

require 'service_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.ShardStatus" do
    optional :hostname, :string, 1
    repeated :locales, :string, 2
    optional :name, :string, 3
    optional :region_tag, :string, 4
    repeated :services, :message, 5, "riotAPI.protos.Service"
    optional :slug, :string, 6
  end
end

module RiotAPI
  module Protos
    ShardStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.ShardStatus").msgclass
  end
end
