# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skin.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Skin" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :num, :int32, 3
  end
end

module RiotAPI
  module Protos
    Skin = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Skin").msgclass
  end
end
