# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spell_vars.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.SpellVars" do
    repeated :coeff, :double, 1
    optional :dyn, :string, 2
    optional :key, :string, 3
    optional :link, :string, 4
    optional :ranksWith, :string, 5
  end
end

module RiotAPI
  module Protos
    SpellVars = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.SpellVars").msgclass
  end
end
