# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Stats" do
    optional :armor, :double, 1
    optional :armorperlevel, :double, 2
    optional :attackdamage, :double, 3
    optional :attackdamageperlevel, :double, 4
    optional :attackrange, :double, 5
    optional :attackspeedoffset, :double, 6
    optional :attackspeedperlevel, :double, 7
    optional :crit, :double, 8
    optional :critperlevel, :double, 9
    optional :hp, :double, 10
    optional :hpperlevel, :double, 11
    optional :hpregen, :double, 12
    optional :hpregenperlevel, :double, 13
    optional :movespeed, :double, 14
    optional :mp, :double, 15
    optional :mpperlevel, :double, 16
    optional :mpregen, :double, 17
    optional :mpregenperlevel, :double, 18
    optional :spellblock, :double, 19
    optional :spellblockperlevel, :double, 20
  end
end

module RiotAPI
  module Protos
    Stats = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Stats").msgclass
  end
end
