# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summoner_id_params.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.SummonerIdParams" do
    repeated :participants, :int64, 1
  end
end

module RiotAPI
  module Protos
    SummonerIdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.SummonerIdParams").msgclass
  end
end
