# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summoner.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Summoner" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :profileIconId, :int32, 3
    optional :revisionDate, :int64, 4
    optional :summonerLevel, :int64, 5
  end
end

module RiotAPI
  module Protos
    Summoner = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Summoner").msgclass
  end
end
