# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team.proto

require 'google/protobuf'

require 'banned_champion_pb'
require 'match_history_summary_pb'
require 'roster_pb'
require 'team_stat_detail_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Team" do
    repeated :bans, :message, 1, "riotAPI.protos.BannedChampion"
    optional :baronKills, :int32, 2
    optional :dominionVictoryScore, :int64, 3
    optional :dragonKills, :int32, 4
    optional :firstBaron, :bool, 5
    optional :firstBlood, :bool, 6
    optional :firstDragon, :bool, 7
    optional :firstInhibitor, :bool, 8
    optional :firstRiftHerald, :bool, 9
    optional :firstTower, :bool, 10
    optional :inhibitorKills, :int32, 11
    optional :riftHeraldKills, :int32, 12
    optional :teamId, :int32, 13
    optional :towerKills, :int32, 14
    optional :vilemawKills, :int32, 15
    optional :winner, :bool, 16
    optional :createDate, :int64, 17
    optional :fullId, :string, 18
    optional :lastGameDate, :int64, 19
    optional :lastJoinDate, :int64, 20
    optional :lastJoinedRankedTeamQueueDate, :int64, 21
    repeated :matchHistory, :message, 22, "riotAPI.protos.MatchHistorySummary"
    optional :modifyDate, :int64, 23
    optional :name, :string, 24
    optional :roster, :message, 25, "riotAPI.protos.Roster"
    optional :secondLastJoinDate, :int64, 26
    optional :status, :string, 27
    optional :tag, :string, 28
    repeated :teamStatDetails, :message, 29, "riotAPI.protos.TeamStatDetail"
    optional :thirdLastJoinDate, :int64, 30
  end
end

module RiotAPI
  module Protos
    Team = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Team").msgclass
  end
end
