# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team_member_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.TeamMemberInfo" do
    optional :inviteDate, :int64, 1
    optional :joinDate, :int64, 2
    optional :playerId, :int64, 3
    optional :status, :string, 4
  end
end

module RiotAPI
  module Protos
    TeamMemberInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.TeamMemberInfo").msgclass
  end
end
