# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tournament_code_update_parameters.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.TournamentCodeUpdateParameters" do
    optional :allowedParticipants, :string, 1
    optional :mapType, :string, 2
    optional :pickType, :string, 3
    optional :spectatorType, :string, 4
  end
end

module RiotAPI
  module Protos
    TournamentCodeUpdateParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.TournamentCodeUpdateParameters").msgclass
  end
end
