# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tournament_registration_parameters.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.TournamentRegistrationParameters" do
    optional :name, :string, 1
    optional :providerId, :int32, 2
  end
end

module RiotAPI
  module Protos
    TournamentRegistrationParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.TournamentRegistrationParameters").msgclass
  end
end
