# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tournament_code_parameters.proto

require 'google/protobuf'

require 'summoner_id_params_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.TournamentCodeParameters" do
    optional :allowedSummonerIds, :message, 1, "riotAPI.protos.SummonerIdParams"
    optional :mapType, :string, 2
    optional :metadata, :string, 3
    optional :pickType, :string, 4
    optional :spectatorType, :string, 5
    optional :teamSize, :int32, 6
  end
end

module RiotAPI
  module Protos
    TournamentCodeParameters = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.TournamentCodeParameters").msgclass
  end
end
