# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tournament_code.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.TournamentCode" do
    optional :code, :string, 1
    optional :id, :int32, 2
    optional :lobbyName, :string, 3
    optional :map, :string, 4
    optional :metaData, :string, 5
    repeated :participants, :int64, 6
    optional :password, :string, 7
    optional :pickType, :string, 8
    optional :providerId, :int32, 9
    optional :region, :string, 10
    optional :spectators, :string, 11
    optional :teamSize, :int32, 12
    optional :tournamentId, :int32, 13
  end
end

module RiotAPI
  module Protos
    TournamentCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.TournamentCode").msgclass
  end
end
