# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "riotAPI.protos.Translation" do
    optional :content, :string, 1
    optional :locale, :string, 2
    optional :updated_at, :string, 3
  end
end

module RiotAPI
  module Protos
    Translation = Google::Protobuf::DescriptorPool.generated_pool.lookup("riotAPI.protos.Translation").msgclass
  end
end
